[package]
name = "rust_wm"
version = "0.1.0"
authors = ["Rasmus Eneman <rasmus@eneman.eu>"]
edition = "2018"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
ipc-channel = "0.12.0"
mir_rs = { path = "../mir_rs"}
serde = "1.0"
xkbcommon = "0.4.0"

[build-dependencies]
cbindgen = "0.9.0"
