[package]
name = "rust_wm"
version = "0.1.0"
authors = ["Rasmus Eneman <rasmus@eneman.eu>"]
edition = "2018"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
mir_rs = { path = "../mir_rs"}

[build-dependencies]
cbindgen = "0.9.0"
