/*
 * AUTOGENERATED - DO NOT EDIT
 *
 * This file is generated from wlr-input-inhibitor-unstable-v1.xml
 * To regenerate, run the “refresh-wayland-wrapper” target.
 */

#ifndef MIR_FRONTEND_WAYLAND_WLR_INPUT_INHIBITOR_UNSTABLE_V1_XML_WRAPPER
#define MIR_FRONTEND_WAYLAND_WLR_INPUT_INHIBITOR_UNSTABLE_V1_XML_WRAPPER

#include <experimental/optional>

#include "mir/fd.h"
#include <wayland-server-core.h>

#include "mir/wayland/wayland_base.h"

namespace mir
{
namespace wayland
{

class ZwlrInputInhibitManagerV1;
class ZwlrInputInhibitorV1;

class ZwlrInputInhibitManagerV1 : public Resource
{
public:
    static char const constexpr* interface_name = "zwlr_input_inhibit_manager_v1";

    static ZwlrInputInhibitManagerV1* from(struct wl_resource*);

    ZwlrInputInhibitManagerV1(struct wl_resource* resource, Version<1>);
    virtual ~ZwlrInputInhibitManagerV1() = default;

    void destroy_wayland_object() const;

    struct wl_client* const client;
    struct wl_resource* const resource;

    struct Error
    {
        static uint32_t const already_inhibited = 0;
    };

    struct Thunks;

    static bool is_instance(wl_resource* resource);

    class Global : public wayland::Global
    {
    public:
        Global(wl_display* display, Version<1>);

        auto interface_name() const -> char const* override;

    private:
        virtual void bind(wl_resource* new_zwlr_input_inhibit_manager_v1) = 0;
        friend ZwlrInputInhibitManagerV1::Thunks;
    };

private:
    virtual void get_inhibitor(struct wl_resource* id) = 0;
};

class ZwlrInputInhibitorV1 : public Resource
{
public:
    static char const constexpr* interface_name = "zwlr_input_inhibitor_v1";

    static ZwlrInputInhibitorV1* from(struct wl_resource*);

    ZwlrInputInhibitorV1(struct wl_resource* resource, Version<1>);
    virtual ~ZwlrInputInhibitorV1() = default;

    void destroy_wayland_object() const;

    struct wl_client* const client;
    struct wl_resource* const resource;

    struct Thunks;

    static bool is_instance(wl_resource* resource);

private:
    virtual void destroy() = 0;
};

}
}

#endif // MIR_FRONTEND_WAYLAND_WLR_INPUT_INHIBITOR_UNSTABLE_V1_XML_WRAPPER
